### ISSUE TITLE
Built plugin contains repo README.md

### ISSUE THREAD

**Issue by dnebauer** [hoelzro/tw-progress-bar#1]
This is not a bug of this repo, but of the plugin as built and packaged at your website [https://hoelz.ro/files/fts.html](https://hoelz.ro/files/fts.html). That plugin contains the `README.md` from this repo. If you look at the _contents_ tab of the plugin in a wiki control panel, it includes a file called:

```
/home/rob/projects/tw-full-text-search/.build-wiki/plugins/progress-bar/README.md
```

**Comment by hoelzro** [comment]
@dnebauer Thanks! I'll remove that later today

**Comment by hoelzro** [comment]
Or I would have if my build environment weren't broken - this might take me a bit!

**Comment by hoelzro** [comment]
Ok, I've managed to fix this!
